routes:
    /:
        controller: channel
        template: home
        filter: tag:-[hash-email,hash-newsletter-issue]
    /membership/: plans
    /membership/welcome/: welcome
    /membership/welcome-paid/: welcome-paid
    /membership/welcome-friends/: welcome-friends
    /membership/exclusive-content/: premium-content
    /newsletter/: newsletter
    /newsletter/welcome/: welcome-newsletter
    /login/: login
    /signup/: signup
    /profile/: profile

collections:
    /posts/:
        permalink: /post/{slug}/
        template: index
        filter: 'tag:hash-en+tag:-[hash-email,hash-newsletter-issue]'
    /issues/:
        permalink: /issue/{slug}/
        template: index
        filter: 'tag:hash-en+tag:hash-newsletter-issue'
    /fr/posts/:
        permalink: /fr/post/{slug}/
        template: index
        filter: 'tag:hash-fr+tag:-[hash-email,hash-newsletter-issue]'
    /fr/issues/:
        permalink: /fr/issue/{slug}/
        template: index
        filter: 'tag:hash-fr+tag:hash-newsletter-issue'

taxonomies:
    tag: /topic/{slug}/
    author: /author/{slug}/
